### ISSUE TITLE
Foming composite pointer type

### ISSUE THREAD

**Issue by FrankHB** [martinmoene/observer-ptr#2]
In `operator<`, the type `W3` can be implemented as `std::common_type_t<W1*, W2*>` when it is available. Seems not hard to emulate it in a pure library way in C++98.

**Comment by martinmoene** [comment]
Thanks @FrankHB .

>std::common_type_t<W1*, W2*> ... Seems not hard to emulate it in a pure library way in C++98.

Can you give a hint?

**Comment by martinmoene** [comment]
Implemented -if easily possible- in [release 0.1.0]().

**Comment by FrankHB** [comment]
The implementation of `common_type` is given explicitly in C++11 20.9.7.6/2. Even the specification in the current standard has been largely modified by [LWG2141](http://wg21.cmeerw.net/lwg/issue2141) and [N3843](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n3843.pdf), the original implementation is still suitable here. So closed as resolved.

**Comment by martinmoene** [comment]
... I was merely wondering about the "Seems not hard to emulate it in a pure library way in C++98.". 

Note for example the complexity of [Boost type_traits common_type](http://www.boost.org/doc/libs/1_50_0/boost/type_traits/common_type.hpp).

Thanks again for bringing it up.

**Comment by FrankHB** [comment]
I think it is not hard because the case here is almost the simplest and as per the code in C++11, they rely on only C++98 features except `decltype`. The latter can be replaced by broadly supported extension as `__typeof__` in this case (when available) for simplicity, but a pure library version is still feasible and not too verbose since you have known the templates arguments are 2 pointers. In boost it is implemented [here](http://www.boost.org/doc/libs/1_60_0_b1/boost/type_traits/detail/composite_pointer_type.hpp). The core logic here is to check the relationship between the pointee types. Strictly speaking, [`is_base_of`](http://www.boost.org/doc/libs/1_60_0/boost/type_traits/is_base_of.hpp) may be trickier if there is no TR1 or intrinsic support, though.
Nevertheless, note that, boost, or any other libraries concerned with such fundamental interface, is often complicated with regard to broken compilers it supports.

**Comment by martinmoene** [comment]
[Release 0.2.0](https://github.com/martinmoene/observer-ptr/releases/tag/v0.2.0) enables ordered comparison of related watched types for GCC when used for C++98, C++03 compilation.

Thanks again.
